/* ************************************
	Author:			Ben Holladay
	AuthorEmail:	bwholladay@gmail.com
	Ward:			Morrisville Ward, Apex North Carolina Stake
	Date:			2018-May
 * ************************************/
function initializeNT()	{
	S[0]  = new Scripture("Matthew 5:14-16",
		"Ye are the light of the world. A city that is set on an hill cannot be hid. Neither do men light a candle, and put it under a bushel, but on a candlestick; and it giveth light unto all that are in the house. Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven.",
		"In the Sermon on the Mount, Jesus taught his disciples basic gospel principles.",
		"True followers of Christ are commanded to set a good example for other people.",
		"Think of what you can do to be a good example to a nonmember you know.",
		"Always remember that the Church is often judged by your behavior as a Latter-day Saint.",
		"Example",
    false);
	S[1]  = new Scripture("Matthew 6:24",
			"No man can serve two masters: for either he will hate the one and love the other; or else he will hold to the one, and despise the other. Ye cannot serve God and mammon.",
		"In the sermon on the Mount, Jesus taught his disciples a 'higher way' of living than the law of Moses.",
		"A faithful Saint does not place any worldly consideration before his love for God.",
		"Make a financial contribution to God's kingdom by saving for your mission or by helping to support another missionary.",
		"Pay your tithing on whatever you earn; then think about what you will do with the rest.",
		"Serve God, Mammon",
    false);
	S[2]  = new Scripture("Matthew 16:15-19",
    "He saith unto them, But whom say ye that I am? And Simon Peter answered and said, Thou art the Christ, the Son of the living God. And Jesus answered and said unto him, Blessed art thou, Simon Bar-jona: for flesh and blood hath not revealed it unto thee, but my Father which is in heaven. And I say also unto thee, That thou art Peter, and upon this rock I will build my church; and the gates of hell shall not prevail against it. And I will give unto thee the keys of the kingdom of heaven: and whatsoever thou shalt bind on earth shall be bound in heaven: and whatsoever thou shalt loose on earth shall be loosed in heaven.",
		"Jesus was alone with his Apostles in northern Galilee on the outskirts of the town of Caesarea Philippi.",
		"Peter know by revelation that Jesus was the Christ.",
		"Bear witness to an investigator that a testimony comes by personal revelation.",
		"Seek continually to strengthen your knowledge that Jesus Christ is the Son of the Living God.",
		"Revelation, Keys",
    false);
	S[3]  = new Scripture("Matthew 25:40",
		"And the King shall answer and say unto them, Verily I say unto you, Inasmuch as ye have done it unto one of the least of these my brethern, ye have done it unto me.",
    "During his last week on earth, Jesus gave careful training and instruction to his Apostles.",
		"When we love and serve others, even those who are not popular, we really serve Jesus Christ.",
		"Look for the chance to help someone in your home or ward area, and then do it.",
		"Think of someone who is suffering or who needs your help at school, and then help that person.",
		"Serve Others",
    false);
	S[4]  = new Scripture("Luke 24:36-39",
    "And as they thus spake, Jesus himself stood in the midst of them, and saith unto them, Peace be unto you. But they were terrified and affrighted, and supposed that they had seen a spirit. And he said unto them, Why are ye troubled? and why do thoughts arise in your hearts? Behold my hands and my feet, that it is I myself: handle me, and see; for a spirit hath not flesh and bones, as ye see me have.",
		"Jesus appeared to his Apostles on the day of his resurrection.",
		"Jesus invited the Apostles to touch his resurrected body as a proof that he was not spirit alone but had a body of flesh and bones.",
		"Bear witness to investigators of the reality of the resurrection and the nature of a resurrected body.",
		"In your prayers, thank your Heavenly Father and Jesus who have made the resurrection a reality.",
		"Resurrected Christ",
    false);
	S[5]  = new Scripture("John 3:5",
		"Jesus answered, Verily, verily, I say unto thee, Except a man be born of water and of the Spirit, he cannot enter into the kingdom of God.",
    "Nicodemus, a Pharisee, came to Jesus at night to ask him questions.",
		"A person must be baptized in water and be cleansed by the power of the Holy Ghost in order to inherit the kingdom of God.",
		"Invite a schoolmate who is interested in the Church to take the missionary lessons to prepare for baptism.",
		"Understand what it means to experience spiritual rebirth by studying the scriptures listed in the topical guide in your Bible under 'Holy Ghost, baptism of.'",
		"Born of Water and Spirit",
    false);
	S[6]  = new Scripture("John 7:17",
    "If any man will do his will, he shall know of the doctrine, whether it be of God, or whether I speak of myself.",
		"Jesus taught in the temple during the feast of tabernacles.",
		"Keeping God's commandments is a sure way to know whether they come from God or not.",
		"Challenge an investigator or friend to test any teaching of the Church by living it to see if it is true.",
		"Begin today to live some commandment that is particularly hard for you, and see if you can learn for yourself that you really are happier when you obey it.",
		"Know Doctrine",
    false);
	S[7]  = new Scripture("John 10:16",
		"And other sheep I have, which are not of this fold: them also I must bring, and they shall hear my voice; and there shall be one fold, and one shepherd.",
    "Jesus portrayed himself as a good shepherd--one who loves, cares for, and protects all his sheep.",
		"Jesus had other sheep (followers) besides those living in Palestine who would hear his voice and be part of his fold.",
		"Invite your investigators to read the Book of Mormon. Point out that one fulfillment of __________ is recorded in 3 Nephi 15:24.",
		"Decide to really listen to the voice of Jesus as you read his word in scriptures and seek him in prayer this week.",
		"Other Sheep",
    false);
	S[8]  = new Scripture("John 14:15",
    "If ye love me, keep my commandments.",
		"Jesus was teaching his Apostles at the Last Supper.",
		"If we truly love the Lord, we will keep his commandments.",
		"Because we love the Lord, we will share the gospel with others.",
		"Express your love for Heavenly Father and his Son each morning and night in prayer, and ask for strength to keep their commandments.",
		"Keep Commandments",
    false);
	S[9] = new Scripture("John 17:3",
		"And this is life eternal, that they might know thee the only true God, and Jesus Christ, whom thou hast sent.",
    "On the night of his betrayal, Jesus prayed to his Father in behalf of his faithful followers.",
		"We can gain eternal life only if we know God and Jesus Christ, his son.",
		"Teach investigators that eternal life will only be available to those who learn what Jesus and the Father are like through studying, understanding, and living the gospel.",
		"Come to know the Father and the Son better by striving to be more like them each day.",
		"Eternal Life, Know God",
    false);
	S[10] = new Scripture("Acts 7:55-56",
    "But he, being full of the Holy Ghost, looked up stedfastly into heaven, and saw the glory of God, and Jesus standing on the right hand of God, And said, Behold, I see the heavens opened, and the Son of man standing on the right hand of God.",
		"Stephen declared his testimony of Christ to the disbelieving Jews and was stoned by them for what they called blasphemy.",
		"The Father and Son are separate and distinct beings.",
		"Explain to nonmembers that Joseph Smith, like Stephen, saw both the Father and the Son and testified they are separate personages.",
		"Strengthen your faith concerning the nature of the Godhead by reading Joseph Smith's account of the First Vision in the Pearl of Great Price.",
		"Godhead",
    false);
	S[11] = new Scripture("Romans 1:16",
		"For I am not ashamed of the gospel of Christ: for it is the power of God unto salvation to every one that believeth; to the Jew first, and also to the Greek.",
    "Paul wrote a letter to the Saints in Rome.",
		"The gospel of Jesus Christ has power to save every person who accepts it, regardless of nationality or background.",
		"Don't be embarrassed or hesitant to express gospel truths or to bear your testimony when it is appropriate.",
		"Always be true to gospel standards, even if they are viewed as unpopular or are ridiculed.",
		"Not Ashamed of Gospel",
    false);
	S[12] = new Scripture("1 Corinthians 10:13",
    "There hath no temptation taken you but such as is common to man: but God is faithful, who will not suffer you to be tempted above that ye are able: but will with the temptation also make a way to escape, that ye may be able to bear it.",
    "The Corinthian Saints lived in a worldly city that was filled with temptations.",
		"The Lord will not allow us to be tempted beyond our capacity to resist.",
		"Reassure your friends that God will help them resist temptation if they are trying to do what's right.",
		"The next time your are tempted, say to yourself, I can resist this temptation with the help of the Lord. Then do so.",
		"Escaping Temptation",
    false);
	S[13] = new Scripture("1 Corinthians 15:20-22",
		"But now is Christ risen from the dead, and become the firstfruits of them that slept. For since by man came death, by man came also the resurrection of the dead. For as in Adam all die, even so in Christ shall all be made alive.",
    "Paul wrote his first letter to the Saints at Corinth from Philippi. (in Christ made alive)",
		"Through the Fall, Adam brought death to all mankind; but through the Atonement, Jesus gave resurrection to all mankind.",
		"Help nonmembers understand that Jesus Christ was the first to be resurrected and made it possible for all the dead to rise.",
		"Show your appreciation for the atonement of Jesus Christ by keeping his commandments.",
		"Resurrection for All",
    false);
	S[14] = new Scripture("1 Corinthians 15:29",
    "Else what shall they do which are baptized for the dead, if the dead rise not at all? why are they then baptized for the dead?",
		"Paul wrote his first letter to the Saints at Corinth from Philippi. (baptism for dead)",
		"Without the resurrection, baptism for the dead would have no purpose.",
		"Help a nonmember understand that the Apostle Paul used the practice of baptism for the dead as an evidence of the resurrection.",
		"Accept an assignment to perform proxy baptisms for the dead in the temple, or submit genealogy sheets so that this work can be done for your own ancestors.",
		"Baptism for the Dead",
    false);
	S[15] = new Scripture("1 Corinthians 15:40-42",
		"There are also celestial bodies, and bodies terrestrial: but the glory of the celestial is one, and the glory of the terrestrial is another. There is one glory of the sun, and another glory of the moon, and another glory of the stars: for one star differeth from another star in glory. So also is the resurrection of the dead. It is sown in corruption; it is raised in incorruption.",
    "Paul wrote his first letter to the Saints at Corinth from Philippi. (resurrection, glory)",
		"Resurrected bodies differ in glory just as the sun, moon, and stars differ in their brightness.",
		"Teach a nonmember friend that in God's house there are many mansions. The glory (or mansion) we inherit depends upon our faith in Christ and our works in this life.",
		"Read D&C 76 and find out what you need to do to inherit a celestial body.",
		"Degrees of Glory",
    false);
	S[16] = new Scripture("Ephesians 4:11-14",
    "And he gave some, apostles; and some, prophets; and some, evangelists; and some, pastors and teachers; For the perfecting of the saints, for the work of the ministry, for the edifying of the body of Christ: Till we all come in the unity of the faith, and of the knowledge of the Son of God, unto a perfect man, unto the measure of the stature of the fulness of Christ: That we henceforth be no more children, tossed to and fro, and carried about with every wind of doctrine, by the sleight of men, and cunning craftiness, whereby they lie in wait to deceive.",
		"Paul wrote to convince the Saints in Ephesus that the Church organization established by God had a purpose.",
		"The priesthood organization is given by God for perfecting the Saints and accomplishing the work of the ministry.",
		"One visible evidence that the Church of Jesus Christ of Latter-day Saints is the true Church is that its organization is patterned after the Church in Jesus' day.",
		"Read and apply the advice given by our present-day prophets and apostles as you try to perfect your life.",
		"Church Organization",
    false);
	S[17] = new Scripture("2 Thessalonians 2:1-3",
		"Now we beseech you, brethern, by the coming of our Lord Jesus Christ, and by our gathering together unto him, That ye be not soon shaken in mind, or be troubled, neither by spirit, nor by word, nor by letter as from us, as that the day of Christ is at hand. Let no man deceive you by any means: for that day shall not come, except there come a falling away first, and that man of sin be revealed, the son of perdition;",
    "Paul was concerned that the Thessalonians might be deceived by false teachers.",
		"There would be an apostasy before the second coming of Christ.",
		"The Church of Jesus Christ of Latter-day Saints represents a necessary restoration of the truths lost through the Apostasy.",
		"Do not be deceived by false teachers or anyone who would lead you astray; follow the ordained prophets of God.",
		"Apostacy",
    false);
	S[18] = new Scripture("2 Timothy 3:1-5",
    "This know also, that in the last days perilous times shall come. For men shall be lovers of their own selves, covetous, boasters, proud, blasphemers, disobedient to parents, unthankful, unholy, Without natural affection, trucebreakers, false accusers, incontinent, fierce, despisers of those that are good, Traitors, heady, highminded, lovers of pleasures more than lovers of God; Having a form of godliness, but denying the power thereof: from such turn away.",
		"Paul's second letter to Timothy was written just before Paul's death.",
		"The last days will be a time of great wickedness.",
		"Seek out and teach the hones in heart who want to overcome the evil practices of our day.",
		"Eliminate any self-centered behavior that keeps you from living close to your Heavenly Father.",
		"Signs of Last Days",
    false);
	S[19] = new Scripture("2 Timothy 3:16-17",
		"All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness: That the man of God may be perfect, throughly furnished unto all good works.",
    "Paul's letter to Timothy encouraged the reading and application of scripture.",
		"The scriptures are inspired of God. The teachings in them, if obeyed, can help us perfect our lives.",
		"Share your testimony of the value of the scriptures with your friends.",
		"As you read the scriptures, mark each passage that is meaningful to you and that you can apply in your life.",
		"Purpose of Scriptures",
    false);
	S[20] = new Scripture("Hebrews 5:4",
    "And no man taketh this honour unto himself, but he that is called of God, as was Aaron.",
		"Paul taught the Hebrew (Jewish) members of the Church about the priesthood.",
		"No man can assume the right to the priesthood of God; he must be properly called and ordained to this power.",
		"Teach that the priesthood of God can be held by all worthy males who are called by the Lord and properly ordained.",
		"Show your appreciation for the priesthood by following the counsel of the priesthood leaders called to preside over you.",
		"Priesthood Authority",
    false);
	S[21] = new Scripture("James 1:5-6",
		"If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him. But let him ask in faith, nothing wavering. For he that wavereth is like a wave of the sea driven with the wind and tossed.",
    "James wrote a letter to the scattered tribes of Israel.",
		"Those who lack wisdom can ask God for help and receive answers.",
		"Tell a friend how Joseph Smith was inspired by this verse in James to go to God in prayer; then tell the story of Joseph Smith's first vision.",
		"Approach you Heavenly Father confidently in prayer, knowing that he will answer you, not scold you.",
		"Ask God",
    false);
	S[22] = new Scripture("James 2:17-18",
		"Even so faith, if it hath not works, is dead, being alone. Yea, a man may say, Thou hast faith, and I have works: shew me thy faith without thy works, and I will shew thee my faith by my works.",
		"James wanted those reading his letter to understand the relationship between faith and works.",
		"Good works demonstrate that one has faith.",
		"Exercise your faith in the gospel of Jesus Christ by preparing now to teach it to others.",
		"Begin today to do something that shows you have faith in a particular principle of the gospel.",
		"Faith and Works",
    false);
	S[23] = new Scripture("Revelation 14:6-7",
		"And I saw another angel fly in the midst of heaven, having the everlasting gospel to preach unto them that dwell on the earth, and to every nation, and kindred, and tongue, and people, Saying with a loud voice, Fear God, and give glory to him; for the hour of his judgement is come: and worship him that made heaven, and earth, and the sea, and the fountains of waters.",
    "As head of the Church after Peter died, John received revelation for the Church.",
		"The everlasting gospel was to be restored by an angel in the latter days.",
		"Bear testimony to a nonmember that the gospel has been restored by heavenly messengers in these latter days.",
		"Thank your Father in Heaven that you live in a day when the gospel has been restored.",
		"Restoration of the Gospel",
    false);
	S[24] = new Scripture("Revelation 20:12-13",
		"And I saw the dead, small and great, stand before God; and the books were opened, which is the book of life: and the dead were judged out of those things which were written in the books, according to their works. And the sea gave up the dead which were in it; and death and hell delivered up the dead which were in them: and they were judged every man according to their works.",
		"While on the Isle of Patmos, John saw a vision of all the dead brought before God to be judged.",
		"All will be judged according to their works out of the books that have been written.",
		"Explain to a nonmember that we believe everyone will stand before God and be judged.",
		"Consider seriously what kind of record you are making by your actions each day.",
		"Judgement",
    false);
}
