/* ************************************
	Author:			Ben Holladay
	AuthorEmail:	bwholladay@gmail.com
	Ward:			Morrisville Ward, Apex North Carolina Stake
	Date:			2018-May
 * ************************************/
	function initializeCH()
	{
		S[0]  = new Scripture("JS-History 1:15-20",
			"It no sooner appeared than I found myself delivered from the enemy which held me bound.  When the light rested upon me I saw two Personages, whose brightness and glory defy all description, standing above me in the air.  One of them spake unto me, calling me by name and said, pointing to  the other--This is My Beloved Son.  Hear Him!  My object in going to inquire of the Lord was to know which of all the sects was right, that I might know which to join.  I was answered that I must join none of them, for they were all wrong; and the Personage who addressed me said that all their creeds were an abomination in his sight; that those professors were all corrupt; that: 'they draw near to me with their lips, but their hearts are far from me, they teach for doctrines the commandments of men, having a form of godliness, but they deny the power thereof.'",
			"Confused by the claims of different churches, young Joseph prayed to God to ask which of all the churches was true",
			"The Father and the Son appeared to Joseph Smith in the Sacred Grove",
			"Using the Joseph Smith story, teach a friend or a nonmember that revelation has not ceased in the latter days.",
			"Bear your testimony that Joseph Smith did see the Father and the Son.",
			"First Vision");
		S[1]  = new Scripture("D&C 1:37:38",
			"Search these commandments, for they are true and faithful, and the prophecies and promises which are in them shall all be fulfilled.  what I the Lord have spoken I have spoken, and I excuse not myself; and though the heavens and the earth pass away, my word shall not pass away, but shall all be fulfilled, whether by mine own voice or by the voice of my servants, it is the same.",
			"At a conference held eighteen months after the Church was organized, the Saints decided to publish some of the revelations Joseph Smith had received.",
			"We are commanded to study the revelations in the Doctrine and Covenants, 'for they are true and faithful' (v. 37).",
			"Share with your parents your feelings that the Doctrine and Covenants is God's word and something you want to study carefully.",
			"Read the entire Doctrine and Covenants this year.",
			"Search the Scriptures");
		S[2] = new Scripture("D&C 8:2-3",
			"Yea, behold, I will tell you in your mind and in your heart, by the Holy Ghost, which shall come upon you and which shall dwell in your heart.  Now, behold, this is the spirit of revelation; behold, this is the spirit by which Moses brought the children of Israel through the Red Sea on dry ground.",
			"During the work of translating the Book of Mormon, Oliver Cowdery became anxious to have the power to translate,  This revelation is a result of his desire.",
			"The Lord reveals his will to us in our minds and hearts by the Holy Ghost.  This is the spirit of revelation.",
			"Help a friend understand that he can know the gospel is true if he asks the Lord.  God will reveal it to him by the Holy Ghost.",
			"Select a principle of the gospel that is difficult to understand, and pray to understand it.  Listen for the prompting that you can feel in your mind or heart.",
			"Spirit of Revelation");
		S[3] = new Scripture("D&C 10:5",
			"Pray always, that you may come off conqueror; yea, that you may conquer Satan, and that you may escape the hands of the servants of Satan that do uphold his work.",
			"After Martin Harris lost 116 pages of the Book of Mormon manuscript, the Prophet Joseph Smith received this revelation, wherein he was told of the plans of those who had the manuscript.",
			"Satan is real, and we must be faithful in our prayers if e are to conquer him.",
			"Share with others the knowledge that we can overcome the temptations of Satan by praying to our Heavenly Father for help.",
			"Identify a personal weakness, and continue to pray to the Father until your have overcome it.",
			"Pray Always");
		S[4]  = new Scripture("D&C 14:7",
			"And, if you keep my commandments and endure to the end you shall have eternal life, which gift is the greatest of all the gifts of God.",
			"Because of persecution in Harmony, Pennsylvania, Joseph and Oliver went to Fayette, New York, to stay with the Whitmers and continue translating the Book of Mormon",
			"Eternal if is the greatest gift of God.",
			"Help a friend who is having trouble keeping God's commandments see the value of being obedient",
			"decide now that your major quest in this life is to work toward obtaining eternal life",
			"Eternal Life, Greatest Gift");
		S[5]  = new Scripture("D&C 18:10,15-16",
			"Remember the worth of souls is great in the sight of God.  And if it so be that you should labor all your days in crying repentance unto this people, and bring, save it be one soul unto me, how great shall be your joy with him in the kingdom of my Father!  And now, if your joy will be great with one soul that you have brought unto me into the kingdom of my Father, how great will be your joy if you should bring many souls unto me!",
			"Joseph Smith, Oliver Cowdery, and David Whitmer sought to know more about the Melchizedek Priesthood.",
			"The worth of souls is great.",
			"Invite an inactive friend to attend church or a Church activity with you.",
			"Remember that your soul is of great worth in the sight of God.",
			"Worth of Souls");
		S[6] = new Scripture("D&C 19:16-19",
			"For behold, I, God, have suffered these things for all, that they might not suffer if they would repent;  But if they would not repent they must suffer even as I;  Which suffering caused myself, even God, the greatest of all, to tremble because of pain, and to bleed at every pore, and to suffer both body and spirit--and would that I might not drink the bitter cup, and shrink--  Nevertheless, glory be to the Father, and I partook and finished my preparations unto the children of men.",
			"Martin Harris went to Joseph Smith seeking further assurance regarding his standing before the Lord.",
			"Jesus Christ suffered for all so that we would not have to suffer if we would repent.",
			"Testify to a friend how repentance and the Atonement have brought you comfort.",
			"Thank Heavenly Father for sending the Savior to make repentance possible.",
			"Repentance, Suffering");
		S[7] = new Scripture("D&C 25:12",
			"For my soul delighteth in the song of the heart; yea, the song of the righteous is a prayer unto me, and it shall be answered with a blessing upon their heads.",
			"This revelation was given to Emma Smith, wife of the Prophet Joseph.  The Church had been organized for about four months but was experiencing intense persecution.",
			"Music plays an important role in worship.  It is a way of communicating with the Lord; he will answer with a blessing.",
			"Be willing to develop and share your musical talents. Help others understand that worthy music can bring one close to God.",
			"Take an inventory of the kinds of music you enjoy, and reject any that is not consistent with Church standards.",
			"Worthy Music");
		S[8]  = new Scripture("D&C 58:26-27",
			"For behold, it is not meet that I should command in all things; for he that is compelled in all things, the same is a slothful and not a wise servant; wherefore he receiveth no reward.  Verily I say, men should be anxiously engaged in a good cause, and do many things of their own free will, and bring to pass much righteousness.",
			"Having recently arrived in Missouri, the Colesville Saints sought additional knowledge about the gathering place.",
			"God does not command us in everything; he expects us to use our agency to do good.",
			"Prepare for a mission by becoming self-starter",
			"Secretly provide some worthwhile Christlike service for someone who needs it.",
			"Agency for Good");
		S[9] = new Scripture("D&C 58:42-43",
			"Behold, he who has repented of his sins, the same is forgiven, and I, the Lord, remember them no more.  By this ye may know if a man repenteth of his sins--behold, he will confess them and forsake them.",
			"Soon after they arrived in Missouri, the Colesville Saints sought additional knowledge about the gathering place.",
			"The Lord will not remember the sins of those who confess their sins and forsake them.",
			"Explain to a worried friend that the Lord will forgive sins that are confessed and forsaken.",
			"Break and forsake a habit that is holding back your spiritual progress.",
			"Confess and Forsake");
		S[10] = new Scripture("D&C 59:9-10",
			"And that thou mayest more fully keep thyself unspotted from the world, thou shalt go to the house of prayer and offer up thy sacraments upon my holy day;  For verily this is a day appointed unto you to rest from your labors, and to pay thy devotions unto the Most High;",
			"Joseph received these instructions after arriving in the chosen land of Missouri.",
			"By observing the Sabbath day with full purpose of heart, we can become unspotted form the world.",
			"Be a good example of keeping the Sabbath day holy each week.",
			"As you partake of the sacrament this coming Sabbath, reflect upon ways to keep yourself unspotted from the world.",
			"Sabbath Day");
		S[11] = new Scripture("D&C 64:9-11",
			"Wherefore, I say unto you, that ye ought to forgive one another; for he that forgiveth not his brother his trespasses standeth condemned before the Lord; for there remaineth in him the greater sin.  I, the Lord, will forgive whom I will forgive, but of you it is required to forgive all men.  And ye ought to say in your hearts--let God judge between me and thee, and reward thee according to thy deeds.",
			"Joseph Smith was preparing to move to Hiram, Ohio, to resume the inspired translation of the Bible.",
			"We are required to forgive everyone and leave judging others to God.",
			"Show by example that you are able to honestly forgive those who hurt you.",
			"Go to a friend who has hurt your feelings, and work out your problems.",
			"Forgive Everyone");
		S[12]  = new Scripture("D&C 64:23",
			"Behold, now it is called today until the coming of the Son of Man, and verily it is a day of sacrifice, and a day for the tithing of my people; for he that is tithed shall not be burned at his coming.",
			"Joseph Smith was preparing to move to Hiram, Ohio, to resume the inspired translation of the Bible.",
			"Those who pay an honest tithing and keep the commandments will not be burned at the Lord's second coming.",
			"Testify to a friend about the blessings of paying a full tithing.",
			"Make a commitment now that you will always pay a full tithe.",
			"Tithing");
		S[13] = new Scripture("D&C 76:22-24",
			"And now, after the many testimonies which have been given of him, this is the testimony, last of all, which we give of him: That he lives!  For we saw him, even on the right hand of God; and we heard the voice bearing record that he is the Only Begotten of the Father--That by him, and through him, and of him, the worlds are and were created, and the inhabitants thereof are begotten sons and daughters unto God.",
			"Joseph Smith and Sidney Rigdon received this vision while working on the translation of the Bible.",
			"Joseph Smith and Sidney Rigdon saw Jesus Christ, the Only Begotten of the Father, who is also the creator of worlds.",
			"Missionaries testify that Joseph Smith did see Jesus Christ, the creator of this world.",
			"Record your testimony of Jesus Christ in your personal journal.",
			"Christ Lives");
		S[14] = new Scripture("D&C 82:3",
			"For of him unto whom much is given much is required; and he who sins against the greater light shall receive the greater condemnation.",
			"Joseph Smith was sustained by the Saints in Missouri as the president of the high priesthood.",
			"The more of the gospel we understand, the more responsibility we have to live it.",
			"Realize that as a member of the true Church, you have a responsibility to share the gospel with others.",
			"Show your appreciation for the gospel by helping more at home.",
			"Much Given, Much Required");
		S[15] = new Scripture("D&C 82:10",
			"I, the Lord, am bound when ye do what I say; but when ye do not what I say, ye have no promise.",
			"Joseph Smith was sustained by the Saints in Missouri as the president of the high priesthood.",
			"The Lord will always keep his promises to us if we keep his commandments.",
			"comfort a confused friend by telling him that God, who cannot lie, is bound to keep his promises.",
			"Seek to obtain the blessings of God by living the commandments.",
			"God's Promises");
		S[16]  = new Scripture("D&C 84:33-39",
			"For whoso is faithful unto the obtaining these two priesthoods of which I have spoken, and the magnifying their calling, are sanctified by the Spirit unto the renewing of their bodies.  They become the sons of Moses and of Aaron and the seed of Abraham, and the church and kingdom, and the elect of God.  And also all they who receive this priesthood receive me, saith the Lord;  for he that receiveth my servants receiveth me;  And he that receiveth me receiveth my Father;  And he that receiveth my Father receiveth my Father's kingdom; therefore all that my Father hath shall be given unto him.  And this is according to the oath and covenant which belongeth to the priesthood.",
			"During a period of great joy when many elders had returned form their missions, Joseph received this revelation on priesthood.",
			"The Father has promised eternal life to those who are faithful in receiving the priesthood and who magnify their callings.",
			"If you were a full-time missionary today, what could you teach new converts about the oath of the priesthood?",
			"Demonstrate that you receive the servants of God by striving to follow the advice of your bishop.",
			"Oath and Covenant");
		S[17] = new Scripture("D&C 88:123-24",
			"See that ye love one another; cease to be covetous; learn to impart one to another as the gospel requires.  Cease to be idle; cease to be unclean; cease to find fault one with another; cease to sleep longer than is needful; retire to thy bed early, that ye may not be weary; arise early, that your bodies and your minds may be invigorated.",
			"This revelation was sent to the Saints in Missouri as an 'olive leaf,' or token of peace.",
			"The Lord commands us to cease all unholy, impure, and idle practices.",
			"Keep yourself clean in body and mind in preparation for missionary work.",
			"Evaluate your sleeping habits, and strive to follow the counsel to go to bed early and rise early.",
			"Righteous Living");
		S[18] = new Scripture("D&C 89:18-21",
			"And all saints who remember to keep and do these sayings, walking in obedience to the commandments, shall receive health in their navel and marrow to their bones;  And shall find wisdom and great treasures of knowledge, even hidden treasures;  And shall run and not be weary, and shall walk and not faint.  And I, the Lord, give unto them a promise, that the destroying angel shall pass by them, as the children of Israel, and not slay them.  Amen.",
			"Joseph was concerned about the elders' using tobacco at meetings of the School of the Prophets.",
			"The lord promises health and hidden treasures of knowledge to those who obey the Word of Wisdom.",
			"Encourage a friend who smokes or drinks to stop doing so.",
			"Make a personal lifelong commitment to abstain from things prohibited in the Word of Wisdom.",
			"Word of Wisdom, Promise");
		S[19] = new Scripture("D&C 121:34-36",
			"Behold, there are many called, but few are chosen.  And why are they not chosen?  Because their hearts are set so much upon the things of this world, and aspire to the honors of men, that they do not learn this one lesson--  That the rights of the priesthood are inseparably connected with the powers of heaven, and that the powers of heaven cannot be controlled nor handled only upon the principles of righteousness.",
			"While Joseph Smith and other Church leaders were cruelly imprisoned in Liberty Jail, Missouri, the Prophet wrote this inspired letter.",
			"The rights of the priesthood are connected with the powers of heaven and can only be used upon the principles of righteousness.",
			"Missionaries should serve because of their love of the Lord and not for personal gain.",
			"The next time your are invited to advise a friend or family member, do not try to force your opinion on him.",
			"Priesthood Power, Called and Chosen");
		S[20]  = new Scripture("D&C 130:18-19",
			"Whatever principle of intelligence we attain unto in this life, it will rise with us in the resurrection.  And if a person gains more knowledge and intelligence in this life through his diligence and obedience than another, he will have so much the advantage in the world to come.",
			"While at Ramus, a Mormon settlement near Nauvoo, Joseph instructed the Saints",
			"The more knowledge and wisdom we gain in this life, the greater advantage we will have in the next.",
			"Read and study diligently so you will be a better missionary.",
			"Decide now that you will not consider your education complete when you finish formal schooling.",
			"Knowledge");
		S[21] = new Scripture("D&C 130:20-21",
			"There is a law, irrevocably decreed in heaven before the foundations of the world, upon which all blessings are predicated--  And when we obtain any blessing from God, it is by obedience to that law upon which it is predicated.",
			"These instructions resulted from questions the Saints asked Joseph Smith. (blessings, obedience)",
			"All blessings are predicated upon obedience to laws.",
			"Realize that your success as a missionary is often based on how well you learn and live the missionary rules.",
			"Choose a commandment you need to keep, and strive to keep it.",
			"Blessings from Obedience");
		S[22] = new Scripture("D&C 130:22-23",
			"The Father has a body of flesh and bones as tangible as man's; the Son also; but the Holy Ghost has not a body of flesh and bones, but is a personage of Spirit.  Were it not so, the Holy Ghost could not dwell in us.  A man may receive the Holy Ghost, and it may descend upon him and not tarry with him.",
			"These instructions resulted from questions the Saints asked Joseph Smith. (GodHead)",
			"The Father and the Son have bodies of flesh and bones, but the Holy Ghost is a personage of spirit.",
			"Teach an investigator about the true nature of the Godhead.",
			"Live today so the Holy Ghost can be with you all day.",
			"Godhead");
		S[23] = new Scripture("D&C 131:1-4",
			"In the celestial glory there are three heavens or degrees;  And in order to obtain the highest, a man must enter into this order of the priesthood [meaning the new and everlasting covenant of marriage];  And if he does not, he cannot obtain it.  He may enter into the other, but that is the end of his kingdom; he cannot have an increase.",
			"William Clayton, the Prophet's scribe, recorded these sacred truths, which Joseph Smith taught in a private gathering.",
			"To obtain the highest of the three degrees in the celestial kingdom, one must enter into the new and everlasting covenant of marriage.",
			"Missionaries teach that the new and everlasting covenant of marriage is essential for exaltation.",
			"Decide now to do what is necessary to be worthy of an eternal marriage.",
			"Celestial Marriage");
		S[24]  = new Scripture("D&C 137:7-10",
			"Thus came the voice of the Lord unto me, saying:  All who have died without a knowledge of this gospel, who would have received it they had been permitted to tarry, shall be heirs of the celestial kingdom of God;  Also all that shall die henceforth without a knowledge of it, who would have received it with all their hearts, shall be heirs of that kingdom;  For I, the Lord, will judge all men according to their works, according to the desire of their hearts.  And I also beheld that all children who die before they arrive at the years of accountability are saved in the celestial kingdom of heaven.",
			"Joseph Smith received this vision in the Kirtland Temple while participating in the administration of part of the special blessing.",
			"Those who died without a knowledge of the gospel but would have accepted and lived it shall inherit the celestial kingdom. Children who die before age eight also enter the celestial kingdom.",
			"Help others know that God has provided a way for everyone who is willing to receive the gospel and become heirs to the celestial kingdom.",
			"Determine now to always take every opportunity to do vicarious work in the temple for those who died without the opportunity to receive needed ordinances.",
			"Heirs of Celestial Kingdom");
	}
