/* ************************************
	Author:			Ben Holladay
	AuthorEmail:	bwholladay@gmail.com
	Ward:			Cary 1st Ward, Apex North Carolina Stake
	Date:			2018-May
 * ************************************/
	function initializeBM()
	{
		S[0]  = new Scripture("1 Nephi 3:7",
			"And it came to pass that I, Nephi said unto my father: I will go and do the things which the Lord hath commanded, for I know that the Lord giveth no commandments unto the children of men, save he shall prepare a way for them that they may accomplish the thing which he commandeth them.",
			"The Lord told Lehi to send his sons back to Jerusalem to get the brass plates from Laban.",
			"The Lord prepares a way for all to keep his commandments.",
			"Help a nonmember friend realize that God will help him obey the commandments to prepare him for baptism.",
			"When the Lord, maybe through your bishop, asks you to do something, have faith that the Lord will open the way to help you do it.",
			"Go and Do; Obedience");
		S[1]  = new Scripture("1 Nephi 19:23",
			"And I did read many things unto them which were written in the books of Moses; but that I might more fully persuade them to believe in the Lord their Redeemer I did read unto them that which was written by the prophet Isaiah; for I did liken all scriptures unto us, that it might be for our profit and learning.",
			"After having obtained the brass plates, Nephi read the scriptures to his family.",
			"The scriptures persuade us to believe in Christ and are 'for our profit and learning.'",
			"Teach an investigator that scriptures have application to us yesterday, today, and tomorrow.",
			"Select some problem in your life and sincerely try to solve it by applying a principle from a scripture.",
			"Liken Scriptures");
		S[2]  = new Scripture("2 Nephi 2:25",
			"Adam fell that men might be; and men are, that they might have joy.",
			"Lehi gave farewell counsel to his son Jacob and taught him about Adam's fall.",
			"Mortality was made possible by Adam's fall; we exist so that we might experience joy.",
			"Explain to a new convert that birth on this earth was a result of Adam's fall.",
			"In your thoughts, your Church discussions, in teaching, and on occasion, in your prayers, express appreciation for Adam.",
			"The Fall, Joy");
		S[3]  = new Scripture("2 Nephi 2:27",
			"Wherefore, men are free according to the flesh; and all things are given them which are expedient unto man.  And they are free to choose liberty and eternal life, through the great Mediator of all men, or to choose captivity and death, according to the captivity and power of the devil; for he seeketh that all men might be miserable like unto himself.",
			"Before he dies, Lehi gave farewell counsel to his son Jacob and taught him about agency.",
			"Men are free to choose freedom and eternal life or captivity and death.",
			"Explain to someone outside the Church that there are consequences to using free agency.",
			"Analyze the consequences of the choices you made today and the ways your choices affect your freedom.",
			"Agency, Eternal Life");
		S[4]  = new Scripture("2 Nephi 9:28-29",
			"O that cunning plan of the evil one!  O the vainness, and the frailties, and the foolishness of men!  When they are learned they think they are wise, and they hearken not unto the counsel of God, for they set it aside, supposing they know of themselves, wherefore, their wisdom is foolishness and it profiteth them not.  And they shall perish.  But to be learned is good if they hearken unto the counsels of God.",
			"After having been called of God and ordained by Nephi, Jacob taught the Nephite people.",
			"To obtain knowledge is good if you follow the counsel of God.",
			"Bear testimony that God's counsel is greater than man's wisdom.",
			"Measure the things you learn in school by what you learn from the scriptures.",
			"Counsel of God");
		S[5]  = new Scripture("2 Nephi 28:7-9",
			"Yea, and there shall be many which shall say: Eat, drink, and be merry, for tomorrow we die; and it shall be well with us. And there shall also be many which shall say: Eat, drink, and be merry; nevertheless, fear God--he will justify in committing a little sin; yea, lie a little, take the advantage of one because of his words, dig a pit for thy neighbor; there is no harm in this; and do all these things, for tomorrow we die; and if it so be that we are guilty, God will beat us with a few stripes, and at last we shall be saved in the kingdom of God. Yea, and there shall be many which shall teach after this manner, false and vain and foolish doctrines, and shall be puffed up in their hearts, and shall seek deep to hide their counsels from the Lord; and their works shall be in the dark.",
			"Nephi prophesied about the worldly philosophies that would be taught in the latter days.",
			"In the last days many will say that it is all right to commit a little sin.",
			"Teach a nonmember that little sins can keep us out of God's kingdom.",
			"Beginning today, stop committing some so-called little sin.",
			"Justify Sin");
		S[6] = new Scripture("2 Nephi 32:3",
			"Angels speak by the power of the Holy Ghost; wherefore, they speak the words of Christ. Wherefore, I said unto you, feast upon the words of Christ; for behold, the words of Christ will tell you all things what ye should do.",
			"Nephi concluded his prophesy by expressing concern that people did not fully understand the doctrine of Christ.",
			"Angels speak by the power of the Holy Ghost, and if we will 'feast upon the words of Christ' they will tell us what we should do.",
			"Help a nonmember understand that sincerely studying the Book of Mormon can lead to a testimony of it's truthfulness.",
			"Approach your study of the Book of Mormon as a spiritual feast. Read, study, visualize, and ponder this great scripture and you will find solutions to many problems you are experiencing.",
			"Words of Christ, Feast");
		S[7] = new Scripture("2 Nephi 32:8-9",
			"And now, my beloved brethren, I perceive that ye ponder still in your hearts; and it grieveth me that I must speak concerning this thing.  For if ye would hearken unto the Spirit which teacheth a man to pray ye would know hat ye must pray; for the evil spirit teacheth him that he must not pray.  But behold, I say unto you that ye must pray always, and not faint; that ye must not perform any thing unto the Lord save in the first place ye shall pray unto the Father in the name of Christ, that he will consecrate thy performance unto thee, that thy performance may be for the welfare of thy soul.",
			"Near the end of his life, Nephi was grieved by man's tendency to misunderstand the things of God.",
			"The Holy Ghost teaches us to pray,  The devil teaches us not to pray.  We should pray always so that all we do may be acceptable unto the Lord.",
			"Help an investigator realize that Satan does not want him to pray to know that Joseph Smith is a prophet.",
			"Pray every day even if you are strongly tempted not to.",
			"Pray Always");
		S[8] = new Scripture("Jacob 2:18-19",
			"But before ye seek for riches, seek ye for the kingdom of God.  And after ye have obtained a hope in Christ ye shall obtain riches, if ye seek them; and ye will seek them for the intent to do good--to clothe the naked, and to feed the hungry, and to liberate the captive, and administer relief to the sick and the afflicted.",
			"After the death of Nephi, the Lord instructed the prophet Jacob to go to the temple and warn the people of the consequences of their wickedness.",
			"Seek first for the things of God, and then use the riches of the world for doing good.",
			"Help a nonmember appreciate the importance of the gospel in comparison to worldly riches.",
			"Put your greatest effort into gaining a testimony of Christ; when you put Christ first, you will use whatever riches you may obtain to do good.",
			"Seek Kingdom, Riches");
		S[9] = new Scripture("Mosiah 2:17",
			"And behold, I tell you these things that ye may learn wisdom; that ye may learn that when ye are in the service of your fellow beings ye are only in the service of your God.",
			"Before giving up the kingdom to his son Mosiah, King Benjamin talked to his people about service.",
			"You serve God when you serve your fellow beings.",
			"Help your friends realize that service to others is how we serve God.",
			"Serve God by serving others in volunteer neighborhood or community service.",
			"Service");
		S[10] = new Scripture("Mosiah 3:19",
			"For the natural man is an enemy to God, and has been from the fall of Adam, and will be, forever and ever, unless he yields to the enticings of the Holy Spirit, and putteth off the natural man and becometh a saint through the atonement of Christ the Lord, and becometh as a child, submissive, meek, humble, patient, full of love, willing to submit to all things which the Lord seeth fit to inflict upon him, even as a child doth submit to his father.",
			"King Benjamin taught his people what an angel had taught him the night before.",
			"The natural (fallen) man is an enemy to god.  By yielding to the Spirit and becoming like a child, we can overcome the natural man.",
			"Show your nonmember friends that without the Holy Spirit we are in a fallen (natural) state and are not close to God.",
			"Listen to the Spirit and be more submissive, patient, and full of love, even when you may be tempted to argue with or rebel against family members.",
			"Natural Man, Saint");
		S[11] = new Scripture("Mosiah 4:30",
			"But this much I can tell you, that if ye do not watch yourselves, and your thoughts, and your words, and your deeds, and observe the commandments of God, and continue in the faith of what ye have heard concerning the coming of our Lord, even unto the end of your lives, ye must perish.  And now, O man, remember, and perish not.",
			"King Benjamin concluded his address from the tower.",
			"We are responsible for our thoughts, words, and deeds.",
			"Teach an investigator that he must repent of and gain control over his bad thoughts, words, and deeds in order to gain eternal life.",
			"Be aware that what you read, see, and hear influences your thoughts and may also influence your words and actions.",
			"Self-control");
		S[12] = new Scripture("Alma 32:21",
			"And now as I said concerning faith--faith is not to have a perfect knowledge of things; therefore if ye have faith ye hope for things which are not seen, which are true.",
			"The poor Zoramites had been denied the right to worship in their synagogues, so Alma preached to them.",
			"Faith is not a perfect knowledge.  It is hope for things which you do not see, but which are true.",
			"Help a new convert realize that faith comes as he studies about the Church.",
			"Develop your faith as you read and ponder the Book of Mormon this year.",
			"Faith");
		S[13] = new Scripture("Alma 34:32-34",
			"For behold, this life is the time for men to prepare to meet God; yea, behold the day of this life is the day for men to perform their labors.  And now, as I said unto you before, as ye have had so many witnesses, therefore, I beseech of you that ye do not procrastinate the day of your repentance until the end; for after this day of life, which is given us to prepare for eternity, behold, if we do not improve our time while in this life, then cometh the night of darkness wherein there can be no labor performed.  Ye cannot say, when ye are brought to that awful crisis, that I will repent, that I will return to my God.  Nay, ye cannot say this; for that same spirit which doth possess your bodies at the time that ye go out of this life, that same spirit will have power to possess your body in that eternal world.",
			"Amulek taught the Zoramites while he was on his mission.",
			"Mortal probation--this life--is given to us to prepare to live in the presence of God; therefore, we must not procrastinate repentance.",
			"Bear testimony that this life is the time to repent and obey Jesus Christ.",
			"Do not put off changing the things in your life that you know you should change.",
			"Procrastination, Repentance");
		S[14] = new Scripture("Alma 37:6-7",
			"Now ye may suppose that this is foolishness in me; but behold I say unto you, that by small and simple things are great things brought to pass; and small means in many instances doth confound the wise.  And the Lord God doth work by means to bring about his great and eternal purposes; and by very small means the Lord doth confound the wise and bringeth about the salvation of many souls.",
			"Alma explained the importance of the sacred records and commanded his son Helaman to take charge of them.",
			"Through simple means the Lord confounds the wise and brings to pass great things.",
			"Help investigators appreciate that the Book of Mormon, one small book among millions, can change the course of the world.",
			"Realize that whether or not you are rich or famous, you can have a great and positive influence on the people around you.",
			"Small Things");
		S[15] = new Scripture("Alma 37:35",
			"O, remember my son, and learn wisdom in thy youth; yea, learn in thy youth to keep the commandments of God.",
			"Alma counseled his son Helaman about his responsibility to teach the people.",
			"Learn to keep the commandments while you are young.",
			"Explain to nonmember friends why we emphasize teaching the gospel to our children.",
			"Learn now to keep the commandments so that they will be part of your nature as you mature in the gospel.",
			"Youth, Keep Commandments");
		S[16] = new Scripture("Alma 41:10",
			"Do not suppose, because it has been spoken concerning restoration, that ye shall be restored from sin to happiness.  Behold, I say unto you, wickedness never was happiness.",
			"Alma encouraged his disobedient son Corianton by explaining the principle of restoration.",
			"Resurrection does not change a person's disposition.  A wicked person cannot experience lasting happiness.",
			"Teach a new member that wickedness can never result in true happiness.",
			"Next time you are tempted to do something you know is wrong, remember that wickedness never leads to lasting happiness.",
			"Wickedness");
		S[17] = new Scripture("Helaman 5:12",
			"And now, my sons, remember, remember that it is upon the rock of our Redeemer, who is Christ, the Son of God, that ye must build your foundation; that when the devil shall send forth his mighty winds, yea, his shafts in the whirlwind, yea, when all his hail and his mighty storm shall beat upon you, it shall have no power over you to drag you down to the gulf of misery and endless wo, because of the rock upon which ye are built, which is a sure foundation, a foundation whereon if men build they cannot fail.",
			"Nephi recounted for his own sons some of the teachings of his father Helaman.",
			"Satan cannot exercise control over those who are built on the Rock--Jesus Christ.",
			"Guide a friend to make the teachings of Christ his foundation.",
			"Determine to build your life on Jesus Christ, the only sure foundation.",
			"Foundation");
		S[18] = new Scripture("3 Nephi 11:29",
			"For verily, verily I say unto you, he that hath the spirit of contention is not of me, but is of the devil, who is the father of contention, and he stirreth up the hearts of men to contend with anger, one with another.",
			"The resurrected Savior explained why disputations about points of doctrine should be avoided.",
			"A person who has the spirit of contention is not of the Savior but is of the devil.",
			"When you discuss the gospel with an investigator, do not contend or argue.",
			"By controlling your tongue and your feelings, you can cease to be contentious with friends and family.",
			"contention");
		S[19] = new Scripture("3 Nephi 27:27",
			"And know ye that ye shall be judges of this people, according to the judgment which I shall give unto you, which shall be just. Therefore, what manner of men ought ye to be? Verily I say unto you, even as I am.",
			"In his final instructions to the Nephite Twelve, Jesus commanded them to pattern their lives after his life.",
			"The Nephite Twelve were called to judge the Nephites. In order to make just judgments, they had to seek to live as Jesus lived.",
			"Help an investigator realize that Jesus is our model and that with his help we can pattern our lives after him.",
			"Study the life of Christ and pick out one of his characteristics to develop this week.",
			"Like Christ");
		S[20] = new Scripture("Ether 12:6",
			"And now, I, Moroni, would speak somewhat concerning these things; I would show unto the world that faith is things which are hoped for and not seen; wherefore, dispute not because ye see not, for ye have no witness until after the trial of your faith.",
			"While abridging the prophet Ether's words on faith, Moroni included some of his own testimony, counsel, and understanding about the subject.",
			"A trial of faith precedes a witness of truth.",
			"Teach a nonmember that a trial of faith is essential to testimony of the gospel of Jesus Christ.",
			"Continue in faith, knowing that a testimony will come or that your testimony will increase as you exercise your faith.",
			"Trial of Faith");
		S[21] = new Scripture("Ether 12:27",
			"And if men come unto me I will show unto them their weakness, I give unto men weakness that they may be humble; and my grace is sufficient for all men that humble themselves before me; for if they humble themselves before me, and have faith in me, then will I make weak things become strong unto them.",
			"In response to Moroni's concern that his readers would mock the weaknesses of his writing, the Lord taught him about personal weaknesses.",
			"Our weaknesses can become strengths if we are humble and have faith in Jesus Christ.",
			"Encourage a friend who is having trouble living the Word of Wisdom to realize that our weaknesses can become strengths.",
			"Strive to overcome a weakness and make it a strength by obeying the Savior.",
			"Weakness to Strength");
		S[22] = new Scripture("Moroni 7:16-17",
			"For behold, the Spirit of Christ is given to every man, that he may know good from evil; wherefore, I show unto you the way to judge; for every thing which inviteth to do good, and to persuade to believe in Christ, is sent forth by the power and gift of Christ; wherefore ye may know with a perfect knowledge it is of God.  But whatsoever thing persuadeth men to do evil, and believe not in Christ, and deny him, and serve not god, then ye may know with a perfect knowledge it is of the devil; for after this manner doth the devil work, for he persuadeth no man to do good, no, not one; neither do his angels; neither do they who subject themselves unto him.",
			"As he neared the end of the record, Moroni included his father Mormon's teachings on the sources of good and evil.",
			"Everything that leads us to do good comes from God.  Every thing that leads us to do evil comes from  the devil.",
			"Bear testimony to someone outside the Church that Jesus is the source of good and that Satan is the source of evil.",
			"Recognize that all good comes of Christ and all evil comes of the devil.  Seek to avoid rationalization in your life.",
			"Recognize Good");
		S[23] = new Scripture("Moroni 7:45",
			"And charity suffereth long, and is kind, and envieth not, and is not puffed up, seeketh not her own, is not easily provoked, thinketh no evil, and rejoiceth not in iniquity but rejoiceth in the truth, beareth all�things, believeth all things, hopeth all things, endureth all things.",
			"After the Nephite nation was destroyed, Moroni recorded some important teachings of his father, Mormon.",
			"Charity is an attribute essential to salvation. It is composed of patience, kindness, thoughtfulness, unselfishness, love for fellowmen, cleanliness, and endurance.",
			"Help a new convert learn the importance of charity and ways to develop charitable attributes.",
			"Pick one of the attributes of charity as a personal goal for this week. As you learn to live a charitable life, you will find eternal happiness.",
			"Charity");
		S[24] = new Scripture("Moroni 10:4-5",
			"And when ye shall receive these things, I would exhort you that ye would ask God, the Eternal Father, in the name of Christ, if these things are not true; and if ye shall ask with a sincere heart, with real intent, having faith in Christ, he will manifest the truth of it unto you by the power of the Holy Ghost. And by the power of the Holy Ghost ye may know the truth of all things.",
			"Moroni closed his record with a promise to all sincere readers.",
			"You can know the Book of Mormon is true by the power of the Holy Ghost.",
			"Challenge nonmember friends to read the Book of Mormon and pray about it.",
			"Read the Book of Mormon, pray sincerely, and have faith in Christ to know if it is of God.",
			"Truth, Ask God");
	}
