/* ************************************
	Author:			Ben Holladay
	AuthorEmail:	bwholladay@gmail.com
	Ward:			Cary 1st Ward, Apex North Carolina Stake
	Date:			2000-May
 * ************************************/
	function initializeOT()
	{
		S[0]  = new Scripture("Moses 1:39",
			"For behold, this is my work and my glory--to bring to pass the immortality and eternal life of man.",
			"Moses was caught up to an exceedingly high mountain and spoke with God face to face.",
			"Heavenly Father's desire for us is to bring about the resurrection of the body (immortality) and to have us live with him as a family in the celestial kingdom (eternal life).",
			"Share with someone outside the Church your feelings that Heavenly Father desires that we obtain eternal life.",
			"You can assist your Heavenly Father in his work by striving for eternal life.",
			"God's Work");
		S[1]  = new Scripture("Moses 7:18",
			"And the Lord called his people Zion, because they were of one heart and one mind, and dwelt in righteousness; and there was no poor among them.",
			"Enoch and his people established the city of Zion before the time of Noah.",
			"Zion consists of people who are as one in their feelings and thoughts and who are totally righteous.",
			"Discuss with your friends how the gospel of Jesus Christ can change their lives and help them grow to a oneness with the people of God.",
			"Seek to live in righteousness and improve your relationships with members of your family and friends so that a proper oneness and love will result.",
			"Zion");
		S[2]  = new Scripture("Abraham 3:22-23",
			"Now the Lord had shown unto me, Abraham, the intelligences that were organized before the world was; and among all these were many of the noble and great ones;  And God saw these souls that they were good, and he stood in the midst of them, and he said: These I will make my rulers; for he stood among those that were spirits, and he saw that they were good; and he said unto me: Abraham, thou art one of them; thou wast chosen before thou wast born.",
			"While in Egypt Abraham recorded this revelation which he received through the Urim and Thummim.",
			"We were spirits in the premortal existence. God selected his noble and great leaders here upon earth.",
			"Help a nonmember understand that before we came to earth we lived as spirit children of God.",
			"Ponder the following statements: I was not an ordinary spirit. I was chosen to help God before I was born.",
			"Premortal Life");
		S[3]  = new Scripture("Genesis 1:26-27",
			"And God said, Let us make man in our image, after our likeness: and let them have dominion over the fish of the sea, and over the fowl of the air, and over the cattle, and over all the earth, and over every creeping thing that creepeth upon the earth.  So God created man in his own image, in the image of God created he him; male and female created he them.",
			"The Lord taught Moses some details concerning the Creation.",
			"All human beings, male and female, are God's children and are created in his own image.  They have dominion over other creatures.",
			"Point out to a nonmember the evidence from God's own words that we are created in his image.",
			"When you pray to Heavenly Father, think of a loving Father, in whose image you are created, who is helping you to govern yourself.",
			"Image of God");
		S[4]  = new Scripture("Genesis 39:9",
			"There is none greater in this house than I; neither hath he kept back any thing from me but thee, because thou are his wife: how then can I do this great wickedness, and sin against God?",
			"After becoming the overseer in Potiphar's household, Joseph was approached repeatedly by Potiphar's wife to commit adultery with her.",
			"Adultery and fornication are serious violations of the commandments of God.",
			"Help an investigator understand that adultery and fornication are still sins against God.",
			"Prepare yourself through personal commitment so that if this temptation ever comes to you, you will respond as Joseph did and not sin against God.",
			"Morally Clean");
		S[5]  = new Scripture("Exodus 20:3-17",
			"Thou shalt have no other gods before me.  Thou shalt not make unto thee any graven image, or any likeness of anything that is in the heaven above, or that is in the earth beneath, or that is in the water under the earth.  Thou shalt not take the name of the Lord thy God in vain; for the Lord will not hold him guiltless that taketh his name in vain.  Remember the sabbath day, to keep it holy.  Honour thy father and thy mother: that thy days may be long upon the land which the Lord thy God giveth thee.  Thou shalt not kill.  Thou shalt not commit adultery.  Thou shalt not steal.  Thou shalt not bear false witness against thy neighbor.  Thou shalt not covet.",
			"After leaving Egypt, the children of Israel were given the Ten Commandments.",
			"The Ten Commandments represent the basic law of God and are the foundation for a righteous life.",
			"Challenge a recent convert to live all of the Ten Commandments. They are as valid today as they were in the days of Moses.",
			"Memorize the Ten Commandments and ask yourself if you are living according to the spirit and letter of each law.",
			"Ten Commandments");
		S[6]  = new Scripture("Exodus 33:11",
			"And the Lord spake unto Moses face to face, as a man speaketh unto his friend. And he turned again into the camp: but his servant Joshua, the son of Nun, a young man, departed not out of the tabernacle.",
			"Even though the tabernacle was moved from the Israelites' camp because of their disobedience, Moses and Joshua were still worthy to enter it.",
			"The God of the Old Testament, Jehovah, was and is a real person. He did speak and will speak to man face-to-face.",
			"Share with a nonmember friend your faith that the Lord can and has revealed himself face-to-face.",
			"Have confidence in the promise that the Lord spoke and still speaks to man.",
			"Revelation, Face to Face");
		S[7]  = new Scripture("Leviticus 19:18",
			"Thou shalt not avenge, nor bear any grudge against the children of thy people, but thou shalt love thy neighbor as thyself: I am the Lord.",
			"As the Israelites traveled in the wilderness, they received instructions from the Lord.",
			"The commandment to love your neighbor is an eternal truth. The Lord requires us to be forgiving, kind, and helpful people.",
			"Teach that the commandment to love was taught in the Old Testament as well as in the New Testament.",
			"Your family members are also neighbors. How can you love them as yourself?",
			"Love Thy Neighbor");
		S[8]  = new Scripture("Deuteronomy 7:3-4",
			"Neither shalt thou make marriages with them; thy daughter thou shalt not give unto his son, nor his daughter shalt thou take unto thy son. For they will turn away thy son from following me, that they may serve other gods: so will the anger of the Lord be kindled against you, and destroy thee suddenly.",
			"To better prepare the Israelites before they entered the promised land, Moses taught them about their relationship to the people they were to conquer.",
			"Marriage to people not of the covenant is not approved by the Lord. It can lead to a loss of faith and testimony.",
			"Discuss with a new member that marrying in the covenant is the Lord's appointed way.",
			"Decide now that when the proper time comes you will not accept anything less than marrying a worthy mate in the temple.",
			"Covenant Marriage");
		S[9] = new Scripture("Joshua 1:8",
			"This book of the law shall not depart out of thy mouth; but thou shalt meditate therein day and night, that thou mayest observe to do according to all that is written therein: for then thou shalt make thy way prosperous, and then thou shalt have good success.",
			"When Joshua was called after Moses to lead the children of Israel, the Lord instructed him.",
			"Meditate upon the scriptures and follow them, and you will prosper and find happiness.",
			"Missionaries teach that as one prophet is taken from his people, the Lord calls another to carry on his work.",
			"Read the scriptures daily, and apply them to your life.",
			"Meditate on the Scriptures");
		S[10] = new Scripture("Joshua 24:15",
			"And if it seem evil unto you to serve the Lord, choose you this day whom ye will serve; whether the gods which your fathers served that were on the other side of the flood, or the gods of the Amorites, in whose land ye dwell: but as for me and my house, we will serve the Lord.",
			"In his farewell address, Joshua challenged the children of Israel to observe principles of service.",
			"We are free to choose whom we will serve, but to serve the Lord is the correct choice.",
			"Prepare to be a missionary by committing your self to serve the Lord in every possible way.",
			"Make a firm commitment this very day that you will serve the Lord in every way you can.",
			"Choose the Lord");
		S[11] = new Scripture("1 Samuel 16:7",
			"But the Lord said unto Samuel, Look not on his countenance, or on the height of his stature; because I have refused him: for the Lord seeth not as a man seeth; for man looketh on the outward appearance, but the Lord looketh on the heart.",
			"Samuel, instructed by the Lord to anoint a king to replace Saul, was impressed by Jesse's eldest son, Eliab.",
			"The Lord judges us by our thoughts and desires rather than by our outward appearance.",
			"How a person may impress us, even if negatively, should not stop us from sharing the gospel with him.",
			"As you look at people, look beyond the outward appearance--clothes, beauty, size--and seek to find the good inner qualities.",
			"Outward Appearance");
		S[12] = new Scripture("Job 19:25-26",
			"For I know that my redeemer liveth, and that he shall stand at the latter day upon the earth: And though after my skin worms destroy this body, yet in my flesh shall I see God:",
			"Even from the depth of the misfortune of losing children, health, and riches, Job declared his testimony that Christ lives.",
			"Jesus does live. He will come again to the earth. All faithful Saints will come forth in the first resurrection.",
			"Bear testimony that you know that Jesus lives and that you know you too will be resurrected.",
			"Study and pray to receive the assurance that the Lord Jesus Christ lives and that we too will be resurrected.",
			"Redeemer Lives, Resurrection");
		S[13] = new Scripture("Psalm 24:3-4",
			"Who shall ascend into the hill of the Lord? or who shall stand in his holy place? He that hath clean hands, and a pure heart; who hath not lifted up his soul unto vanity, nor sworn deceitfully.",
			"David expressed his feelings of reverence for the Lord's majesty.",
			"Only those who repent of their sins and live pure lives are worthy to go to the temple and to enter the celestial kingdom.",
			"Missionaries must have clean hands and pure hearts.",
			"Demonstrate your purity of heart by not telling or listening to dirty jokes or stories.",
			"Cleanliness");
		S[14] = new Scripture("Proverbs 3:5-6",
			"Trust the Lord with all thine heart: and lean not unto thine own understanding. In all thy ways acknowledge him. and he shall direct thy paths.",
			"Solomon and other wise Hebrews wrote thoughts and saying called proverbs.",
			"If we will place our total trust in the Lord, he will guide us in our decisions and direct us in living a righteous life.",
			"When faced with the decision of whether to be baptized or not, the investigator is often challenged to trust in the Lord with all his heart.",
			"Make a special effort this week to give credit and thanks to the Lord for his blessings to you.",
			"Trust the Lord");
		S[15] = new Scripture("Isaiah 1:18",
			"Come now, and let us reason together, saith the Lord: though your sins be as scarlet, they shall be as white as snow; though they be red like crimson, they shall be as wool.",
			"In approximately 730 B.C. the Lord, through Isaiah, called upon the disobedient people of Judah to forsake their evil ways.",
			"Through our complete repentance and the atoning blood of Christ, even our serious sins can be completely forgiven.",
			"Before going on a mission, you should seek to repent of all your sins and resolve serious ones with the proper authorities.",
			"Forsake and confess your sins and pray to your Heavenly Father with a broken heart and contrite spirit, seeking forgiveness.",
			"Repentance, Forgiveness");
		S[16] = new Scripture("Isaiah 29:13-14",
			"Wherefore the Lord said, Forasmuch as this people draw near me with their mouth, and with their lips do honour me, but have removed their heart far from me, and their fear toward me is taught by the precept of men: Therefore, behold, I will proceed to do a marvellous work and among this people, even a marvellous work and a wonder: for the wisdom of their wise men shall perish, and the understanding of their prudent men shall be hid.",
			"In approximately 700 B.C., Isaiah prophesied of the restoration of the gospel in the last days.",
			"The marvelous work and a wonder spoken of here is the restoration of the gospel to the earth in the latter days.",
			"Bear witness to a nonmember that the Lord's marvellous work and wonder is taking place today and has included the restoration of the priesthood and the true Church.",
			"When you draw near to the Lord in prayer, make sure that your heart is sincere and that you do not just give lip service.",
			"Marvelous Work and Wonder");
		S[17] = new Scripture("Isaiah 53:3-5",
			"He is despised and rejected of men; a man of sorrows, and acquainted with grief: and we hid as it were our faces from him;; he was despised, and we esteemed him not. Surely he hath borne our griefs, and carried our sorrows: yet we did esteem him stricken, smitten of God, and afflicted. But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed.",
			"Isaiah prophesied about the suffering and rejection of Messiah (the Christ).",
			"The Son of God will be despised and rejected; however, through his suffering for our sins we can be forgiven and healed.",
			"A central message missionaries teach is that Jesus is the Christ, our Savior, and the Messiah foretold by Isaiah.",
			"Show your appreciation for what Jesus suffered by repenting of the sins you need to overcome.",
			"Jesus Christ");
		S[18] = new Scripture("Isaiah 55:8-9",
			"For my thoughts are not your thoughts, neither are your ways my ways, saith the Lord. For as the heavens are higher that the earth, so are my ways higher than your ways, and my thoughts than your thoughts.",
			"The kingdom of Judah did not want to listen to the Lord. They wanted to follow their own wisdom. Isaiah called them to repentance.",
			"Man cannot totally comprehend the thoughts and purposes of the Almighty.",
			"Help a friend understand that the Lord may do certain things that are hard for us to understand, but that we can always trust his greater wisdom.",
			"Trust the Lord and follow him lovingly, seeking to think and act like him.",
			"Higher Ways and Thoughts");
		S[19] = new Scripture("Jeremiah 16:16",
			"Behold, I will send for many fishers, saith the Lord, and they shall fish them; and after will I send for many hunters, and they shall hunt them from every mountain, and from every hill, and out of the holes of the rocks.",
			"Jeremiah prophesied to the Jews about he last days.",
			"In the last days, the Lord will send missionaries to gather Israel.",
			"Missionaries work hard 'fishing and hunting' for the honest in heart.",
			"You can assist in the gathering of Israel by finding out which of your friends are interested in the gospel and teaching them by word and by example.",
			"Missionary Work");
		S[20] = new Scripture("Ezekiel 37:15-17",
			"The word of the Lord came again unto me, saying, Moreover, thou son of man, take thee one stick, and write upon it, For Judah, and for the children of Israel his companions: then take another stick, and write upon it, For Joseph, the stick of Ephraim, and for all the house of Israel his companions: And join them one to another into one stick; and they shall become one in thine hand.",
			"During the kingdom of Judah's captivity in Babylon, Ezekiel prophesied of latter-day events.",
			"The Bible is the stick of Judah, and the Book of Mormon is the stick of Joseph. They have been joined together as one in the hand of the true believers.",
			"Bear your witness that the Book of Mormon is joined with the Bible as a second witness of Jesus Christ.",
			"Make the Bible and the Book of Mormon one in your life by using the cross-references and aids from each that help clarify gospel truths.",
			"Bible, Book of Mormon");
		S[21] = new Scripture("Daniel 2:44-45",
			"And in the days of these kings shall the God of heaven set up a kingdom, which shall never be destroyed: and the kingdom shall not be left to other people, but is shall break in pieces and consume all these kingdoms, and it shall stand forever. Forasmuch as thou sawest that the stone was cut out of the mountain without hands, and that it brake in pieces the iron, the brass, the clay, the silver, and the gold; the great God hath made known to the king what shall come to pass hereafter: and the dream is certain, and the interpretation thereof sure.",
			"After the wise men of the kingdom failed to interpret the meaning of the king's dream, Daniel was asked to interpret it.",
			"The kingdom of God in the last days is compared to a stone cut out of the mountain without hands. The stone will ultimately break in pieces all earthly kingdoms and fill the earth.",
			"Bear testimony to a nonmember that Daniel prophesied about the establishment and destiny of The Church of Jesus Christ of Latter-day Saints.",
			"The Church is more than a nice social organization to belong to; it is the kingdom of God.",
			"Kingdom of God");
		S[22] = new Scripture("Amos 3:7",
			"Surely the Lord God will do nothing, but he revealeth his secret unto his servants the prophets.",
			"In the eighth century B.C., Amos taught this truth while prophesying against the sins of Israel.",
			"Whenever the Lord desires to reveal his will for the world, he does so through his chosen prophets.",
			"As you obey the living prophet today, you are a living example of one who accepts revelations from God through his servants the prophets.",
			"The First Presidency and the Twelve Apostles are God's prophets on earth today. Listen to their speeches and read their articles to learn what the Lord wants you to do.",
			"Prophets");
		S[23] = new Scripture("Malachi 3:8-10",
			"Will a man rob God? Yet ye have robbed me. But ye say, Wherein have we robbed thee? In tithes and offerings. Ye are cursed with a curse: for ye have robbed me, even this whole nation. Bring ye all the tithes into the storehouse, that there may be meat in mine house, and prove me now herewith, saith the Lord of hosts, if I will not open you the windows of heaven, and pour you out a blessing, that there shall not be room enough to receive it.",
			"The disobedient kingdom of Judah had neglected to pay tithes and offerings to the Lord.",
			"The payment of tithes and offerings is a commandment. Those who pay them will have the windows of heaven opened to them in blessings.",
			"Share with a recent convert your testimony of faith or an experience showing the blessings of paying tithing.",
			"Resolve to pay your tithing the rest of your life and give the Lord the opportunity to open the windows of heaven and bless you.",
			"Tithes and Offerings");
		S[24] = new Scripture("Malachi 4:5-6",
			"Behold, I will send you Elijah the prophet before the coming of the great and dreadful day of the Lord: And he shall turn the heart of the fathers to the children, and the heart of the children to their fathers, lest I come and smite the earth with a curse.",
			"Approximately four hundred years before the birth of Christ, Malachi spoke for the Lord.",
			"Malachi prophesied that Elijah would return before the Second Coming and would restore the keys of turning the hearts of parents and children to each other and opening the door for genealogy and temple work.",
			"Bear witness that Elijah has indeed returned to the earth and restored the sealing keys of the priesthood.",
			"Complete your own personal pedigree chart and as many family group sheets as possible to demonstrate that your heart is turned to your ancestors.",
			"Sealing Power");
	}
